159
SELECT * FROM TB_POINT;
SELECT * FROM TB_CUSTOMER;
SELECT CUSTOMER_CD,
     (SELECT S1.CUSTOMER_NM FROM TB_CUSTOMER S1 WHERE S1.CUSTOMER_CD=S2.CUSTOMER_CD) AS 고객명, TOT_POINT FROM
    ( SELECT CUSTOMER_CD,TOT_POINT FROM (
         SELECT CUSTOMER_CD, SUM(POINT) AS TOT_POINT FROM TB_POINT WHERE CUSTOMER_CD>'2019000' GROUP BY CUSTOMER_CD  )
    WHERE TOT_POINT>10000 ) S2
;
159방법2
SELECT S1.CUSTOMER_CD,S1.CUSTOMER_NM, TOT_POINT FROM TB_CUSTOMER S1,
    ( SELECT CUSTOMER_CD,TOT_POINT FROM (
         SELECT CUSTOMER_CD, SUM(POINT) AS TOT_POINT FROM TB_POINT WHERE CUSTOMER_CD>'2019000' GROUP BY CUSTOMER_CD  )
    WHERE TOT_POINT>10000 ) S2
WHERE S1.CUSTOMER_CD=S2.CUSTOMER_CD;

162
SELECT CUSTOMER_CD, SEQ_NO, POINT_MEMO, POINT, REG_DTTM FROM TB_POINT S2
WHERE EXISTS (
    SELECT 'a' FROM TB_CUSTOMER S1
    WHERE S1.CUSTOMER_CD=S2.CUSTOMER_CD AND S1.MW_FLG='M');
    
  
165 
SELECT * FROM TB_GRADE;
SELECT * FROM TB_GRADE WHERE CLASS_CD=:V1; --조건입력창에 조건값을 임력해 검사함.
167
REM 주석
--주석
/*주석*/

--170
SELECT * FROM TB_GRADE;
SELECT * FROM TB_CUSTOMER WHERE CUSTOMER_NM LIKE '%'||:고객명|| '%' AND MW_FLG=:성별;    
--172
SELECT * FROM TB_GRADE;
SELECT STUDENT_NM,KOR FROM TB_GRADE WHERE KOR>=90;
SELECT STUDENT_NM,ENG FROM TB_GRADE WHERE ENG>=90;
SELECT STUDENT_NM,MAT FROM TB_GRADE WHERE MAT>=90;

SELECT STUDENT_NM FROM TB_GRADE WHERE KOR>=90 UNION 
SELECT STUDENT_NM FROM TB_GRADE WHERE ENG>=90; --UNION

SELECT STUDENT_NM FROM TB_GRADE WHERE KOR>=90 UNION ALL
SELECT STUDENT_NM FROM TB_GRADE WHERE ENG>=90;

SELECT STUDENT_NM FROM TB_GRADE WHERE KOR>=90 INTERSECT
SELECT STUDENT_NM FROM TB_GRADE WHERE ENG>=90;

SELECT STUDENT_NM FROM TB_GRADE WHERE MAT>=90 MINUS
SELECT STUDENT_NM FROM TB_GRADE WHERE KOR>=90;

--179p
--2024.7.11
SELECT CURRENT_DATE FROM DUAL; --현재일시
select sysdate from dual;--현재일시
--180
SELECT SYSDATE, CURRENT_DATE FROM DUAL; --현재일자 확인
SELECT SYSDATE, SYSDATE -30, SYSDATE +60 FROM DUAL;--현재일 기준 30일 이전, 60일 이후
--181
SELECT SYSDATE, SYSDATE+((1/(86400/60/60))*3) AS CHG_DTTM FROM DUAL;--현재일시 기준 3시간 이후 날짜

SELECT TO_CHAR(SYSDATE,'YYYYMMDD') AS TODAY FROM DUAL;--현재일시를 YYYYMMDD로 출력
--날짜를 문자로 바꾸기
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD HH:MI:SS') AS TODAY FROM DUAL; --182
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS') AS TODAY FROM DUAL; --183 24시간 형태로 표현
--날짜형식 문자열을 날짜로 변경
SELECT TO_DATE('20240311') AS DT FROM DUAL;
SELECT TO_DATE('20240711')+200 FROM DUAL;

SELECT TO_DATE('20240711')+200 DTTM FROM DUAL;
SELECT TO_CHAR(TO_DATE('20240711')+200,'YYYY-MM-DD') FROM DUAL;

--185
SELECT * FROM TB_CUSTOMER;

SELECT CUSTOMER_CD, CUSTOMER_NM, MW_FLG,BIRTH_DAY, ROUND((SYSDATE-TO_DATE(BIRTH_DAY))/365,1) AS 나이
FROM TB_CUSTOMER
WHERE CUSTOMER_CD IN('2017042','2017053'); --185 나이구하기

SELECT NEXT_DAY(SYSDATE,'일요일') FROM DUAL; --186

SELECT TO_CHAR(NEXT_DAY('20240801',4),'YYYY-MM-DD') FROM DUAL; --지정일 이후의 해당요일(4=목요일) 확인
SELECT LAST_DAY('20230215') FROM DUAL;--해당달의 마지막 날짜확인
--187
SELECT NEXT_DAY('20190820', '금요일') FROM DUAL;
SELECT TO_CHAR(NEXT_DAY('20190820','금요일'),'YYYY-MM-DD')AS NEXT_DAY FROM DUAL; 

SELECT TO_CHAR(NEXT_DAY('20190820','월요일'),'YYYY-MM-DD')AS NEXT_DAY FROM DUAL;
--LAST_DAY() : 특정월의 마지막 날짜를 구하는 기능
SELECT LAST_DAY('20240723') FROM DUAL;
--189p
SELECT TO_CHAR(LAST_DAY(TO_DATE('20240101')),'DD') FROM DUAL; --2024년 1월 1일의 마지막 날짜 구하기
--2024년도 각 월의 마지막 날짜 구하기
SELECT SUBSTR(S1.DATE2019,1,6) AS MONTH, TO_CHAR(LAST_DAY(TO_DATE(S1.DATE2019)),'DD') AS LAST_DAY FROM
    (
    SELECT '20190101' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20190201' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20190301' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20190401' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20190501' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20190601' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20190701' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20190801' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20190901' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20191001' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20191101' AS DATE2019 FROM DUAL UNION ALL
    SELECT '20191201' AS DATE2019 FROM DUAL)S1;

190
SELECT ADD_MONTHS(SYSDATE,4) FROM DUAL;--지정일에 4개월 더하기
SELECT ADD_MONTHS(SYSDATE,-2) FROM DUAL;--지정일에 2개월 전
--192 현재 일시를 기준으로 2개월 전과 2개월 후의 날짜를 'YYYY-MM-DD'형식으로 출력하시오.
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD'),
    TO_CHAR(ADD_MONTHS(SYSDATE,-2),'YYYY-MM-DD'),
    TO_CHAR(ADD_MONTHS(SYSDATE,+2),'YYYY-MM-DD')
FROM DUAL;
--192
SELECT MONTHS_BETWEEN(TO_DATE('20240101','YYYYMMDD'),SYSDATE) FROM DUAL;--날짜 차이를 개월로 구하기

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH:MI:SS') AS CUR_DTTM,
    ROUND(MONTHS_BETWEEN(TO_DATE('20191005','YYYYMMDD'),TO_DATE('20190820','YYYYMMDD')),2) AS MONTH_TERM1,
    ROUND(MONTHS_BETWEEN(TO_DATE('20190703','YYYYMMDD'),TO_DATE('20191208','YYYYMMDD')),2) AS MONTH_TERM2,
    ROUND(MONTHS_BETWEEN(SYSDATE,TO_DATE('20190701','YYYYMMDD')),2) AS MONTH_TERM3
    FROM DUAL;

--194
SELECT * FROM TB_POINT;
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD')AS 현재일자 FROM DUAL;
SELECT CUSTOMER_CD,SEQ_NO,POINT_MEMO,POINT, REG_DTTM,
    TO_CHAR(SYSDATE,'YYYY-MM-DD')AS 현재일자,
    ROUND(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(REG_DTTM,1,8),'YYYYMMDD')),1) AS 개월차
    FROM TB_POINT WHERE CUSTOMER_CD='2019001';