//2024.10.8 
270P
DENSE_RANK():중복 순위를 부여하고 그 이후는 순차적인 순위를 구함
SELECT * FROM TB_GRADE_07;

SELECT TEST_CD,KOR,DENSE_RANK() OVER (ORDER BY KOR DESC) AS 순위 
   FROM TB_GRADE_07 ORDER BY KOR DESC;
   
RANK() WITHIN :  순번을 구한 후 위치를 구하는 함수
SELECT RANK(96) WITHIN GROUP(ORDER BY KOR DESC) AS "96점 위치" FROM TB_GRADE_07;

273P
FIRST_VALUE() : 그룹을 만들고 정렬필드명으로 정렬한 필드명의 첫 번째 위치의 값을 구함
SELECT * FROM TB_GRADE;

SELECT CLASS_CD, STUDENT_NO, STUDENT_NM,KOR,
     FIRST_VALUE(KOR) OVER (PARTITION BY CLASS_CD ORDER BY KOR DESC) AS "반별 최대점수"
     FROM TB_GRADE ORDER BY CLASS_CD, KOR DESC;
     
275P
행 정보 관련 함수 : 현재 레코드 행에서 이전 레코드 행이나 다음 레코드 행의 값을 구하거나 그룹으로 지정한 여러 레코드 필드 값을 한 레코드 행으로 보이는 명령어
SELECT * FROM TB_TRAIN_TM;
LEAD: 다음 레코드행
SELECT TRAIN_NO, RUN_ORDR, STATION_NM AS 현재역명, 
    LEAD(STATION_NM) OVER(PARTITION BY TRAIN_NO ORDER BY RUN_ORDR) AS "다음역명"
    FROM TB_TRAIN_TM;
    
277p
LAG(): 이전 레코드 행
SELECT TRAIN_NO, RUN_ORDR, STATION_NM AS 현재역명,
    LEAD(STATION_NM) OVER(PARTITION BY TRAIN_NO ORDER BY RUN_ORDR) AS "다음역명",
    LAG(STATION_NM) OVER(PARTITION BY TRAIN_NO ORDER BY RUN_ORDR) AS "이전역명"
    FROM TB_TRAIN_TM;

279p
SELECT TRAIN_NO,SUBSTR(XMLAGG(XMLELEMENT(X,',',STATION_NM) ORDER BY RUN_ORDR).EXTRACT('//text()'),2) AS "역목록"
    FROM TB_TRAIN_TM GROUP BY TRAIN_NO;
    
282p
CREATE TABLE TB_GRADE_2019
( TEST_MONTH CHAR(2 BYTE) NOT NULL,
  TEST_CD CHAR(3 BYTE) NOT NULL,
  KOR NUMBER(3),
  ENG NUMBER(3),
  MAT NUMBER(3)
  );
  
  CREATE UNIQUE INDEX PK_TB_GRADE_2019 ON TB_GRADE_2019 (TEST_MONTH, TEST_CD);
  
  ALTER TABLE TB_GRADE_2019 ADD (CONSTRAINT PK_TB_GRADE_2019 PRIMARY KEY (TEST_MONTH, TEST_CD));
  
INSERT INTO TB_GRADE_2019 VALUES('01','T01',92,98,84);
INSERT INTO TB_GRADE_2019 VALUES('01','T02',84,94,90);

SELECT * FROM TB_GRADE_2019;

RENAME TB_GRADE_2019 TO TB_2019_GRADE;
SELECT * FROM TB_2019_GRADE;
RENAME TB_2019_GRADE TO TB_GRADE_2019;
ALTER TABLE TB_GRADE_2019 ADD (TOT NUMBER(5) NULL);
ALTER TABLE TB_GRADE_2019 ADD (AVG NUMBER(5,1) NULL);

DESC TB_GRADE_2019;

MODIFY- 속성변경
ALTER TABLE TB_GRADE_2019 MODIFY(TOT NUMBER(6));
ALTER TABLE TB_GRADE_2019 RENAME COLUMN TOT TO SUM;
ALTER TABLE TB_GRADE_2019 DROP COLUMN SUM;

SELECT * FROM TB_GRADE_2019;

테이블은 남기고 데이터를 지우는 함수:TRUNCATE TABLE
TRUNCATE TABLE TB_GRADE_2019;

테이블 삭제: DROP
DROP TABLE TB_GRADE_2019;
FLASHBACK TABLE TB_GRADE_2019 TO BEFORE DROP;

[뷰]: 연관 테이블의 내용이 바뀌면 자동으로 값을 갱신해주는 가상 테이블

고객 테이블의 고객코드, 고객명, 성별, 생년월일, 전화번호 필드와 
포인트 테이블의 일렬번호, 포인트 내용, 포인트 필드로 구성된 뷰를 작성하시오.

