select * from tb_grade;
select * from tb_class_info;
select * from tb_grade_08;
select * from tb_grade_09;
select * from tb_customer;
select * from tb_point;
1.
SELECT CI.CLASS_NM, G.STUDENT_NO, G.STUDENT_NM, G.KOR, G.ENG, G.MAT
FROM TB_CLASS_INFO CI, TB_GRADE G
WHERE CI.CLASS_CD = G.CLASS_CD;

2.
SELECT CI.CLASS_NM
FROM TB_CLASS_INFO CI, TB_GRADE G
WHERE CI.CLASS_CD = G.CLASS_CD 
AND G.STUDENT_NM = '서유리';

3.
SELECT G.STUDENT_NM, G.KOR, G.ENG, G.MAT
FROM TB_CLASS_INFO CI, TB_GRADE G
WHERE CI.CLASS_CD = G.CLASS_CD
AND CI.CLASS_NM='단과반';

4.
SELECT CI.CLASS_NM, G.STUDENT_NM 
FROM TB_CLASS_INFO CI, TB_GRADE G
WHERE CI.CLASS_CD = G.CLASS_CD
AND G.KOR=100;

5.
SELECT CI.CLASS_NM, G.STUDENT_NM
FROM TB_CLASS_INFO CI, TB_GRADE G
WHERE CI.CLASS_CD = G.CLASS_CD
AND G.STUDENT_NO=2;

6. 
SELECT G.STUDENT_NM, G.KOR
FROM TB_CLASS_INFO CI, TB_GRADE G
WHERE CI.CLASS_CD = G.CLASS_CD
AND CI.CLASS_NM='일반인반'
AND G.KOR>=90;

7.
SELECT CI.CLASS_NM, G.STUDENT_NM, G.MAT
FROM TB_CLASS_INFO CI, TB_GRADE G
WHERE CI.CLASS_CD = G.CLASS_CD
AND (CI.CLASS_NM='종합입시반' OR G.MAT>=80);

8.
SELECT CLASS_CD,SUM(KOR), SUM(ENG), SUM(MAT), 
ROUND(AVG(KOR),1), ROUND(AVG(ENG),1), ROUND(AVG(MAT),1)
FROM TB_GRADE
GROUP BY CLASS_CD
HAVING AVG(KOR)>=80;

9.
SELECT G8.TEST_CD
FROM TB_GRADE_08 G8, TB_GRADE_09 G9
WHERE G8.TEST_CD = G9.TEST_CD;

10.
SELECT G9.ENG
FROM TB_GRADE_08 G8, TB_GRADE_09 G9
WHERE G8.TEST_CD = G9.TEST_CD
AND G8.ENG = 100;

11. 
SELECT CUSTOMER_CD,CUSTOMER_NM, BIRTH_DAY, PHONE_NUMBER
FROM TB_CUSTOMER
WHERE CUSTOMER_CD>=2019000
AND MW_FLG='W';

12. 
SELECT CUSTOMER_CD,CUSTOMER_NM, BIRTH_DAY, PHONE_NUMBER
FROM TB_CUSTOMER
WHERE BIRTH_DAY<'19900101'
AND MW_FLG='M';

13.
SELECT CUSTOMER_CD,CUSTOMER_NM, BIRTH_DAY, PHONE_NUMBER
FROM TB_CUSTOMER
WHERE MW_FLG='M'
AND (TOTAL_POINT>=20000 OR BIRTH_DAY<'19700101');

14. 
SELECT CUSTOMER_CD,CUSTOMER_NM, MW_FLG, BIRTH_DAY, PHONE_NUMBER, EMAIL
FROM TB_CUSTOMER
WHERE (MW_FLG='M' AND EMAIL IS NULL) 
OR (MW_FLG='W' AND EMAIL IS NOT NULL);

15.
SELECT P.POINT_MEMO, C.CUSTOMER_NM
FROM TB_CUSTOMER C, TB_POINT P
WHERE P.CUSTOMER_CD=C.CUSTOMER_CD
AND P.POINT>=10000;

16.
SELECT C.CUSTOMER_CD, C.CUSTOMER_NM,P.POINT_MEMO
FROM TB_CUSTOMER C, TB_POINT P
WHERE P.CUSTOMER_CD=C.CUSTOMER_CD
AND P.REG_DTTM LIKE '2017%';

17.
SELECT C.CUSTOMER_CD, C.CUSTOMER_NM, C.MW_FLG, C.PHONE_NUMBER
FROM TB_CUSTOMER C, TB_POINT P
WHERE P.CUSTOMER_CD=C.CUSTOMER_CD
AND P.POINT_MEMO LIKE '드라이기%';

18.
SELECT C.CUSTOMER_CD, C.CUSTOMER_NM, P.POINT_MEMO
FROM TB_CUSTOMER C, TB_POINT P
WHERE P.CUSTOMER_CD=C.CUSTOMER_CD
AND C.TOTAL_POINT>=15000;

19.
SELECT C.CUSTOMER_CD, C.CUSTOMER_NM, CASE C.MW_FLG WHEN 'M' THEN '남' WHEN 'W' THEN '여' END AS 성별, C.PHONE_NUMBER
FROM TB_CUSTOMER C, TB_POINT P
WHERE P.CUSTOMER_CD=C.CUSTOMER_CD
AND P.POINT_MEMO LIKE '냉장고%' AND C.TOTAL_POINT>=15000;

20. 
SELECT C.CUSTOMER_CD, C.CUSTOMER_NM, C.TOTAL_POINT
FROM TB_CUSTOMER C, TB_POINT P
WHERE P.CUSTOMER_CD=C.CUSTOMER_CD
AND C.CUSTOMER_CD LIKE '2019%'
AND P.POINT_MEMO LIKE '드라이기%';