236 13장 비교함수
select * from tb_customer;
SELECT CUSTOMER_CD,CUSTOMER_NM, MW_FLG, DECODE(MW_FLG,'M','남성','W','여성') AS "성별" FROM TB_CUSTOMER;
SELECT * FROM TB_ETC_INFO;
SELECT CUSTOMER_CD,CUSTOMER_ENG_NM,ITEM_LIST,
    SUBSTR(DECODE(INSTR(ITEM_LIST,'S01'),0,'',',의류잡화')||
           DECODE(INSTR(ITEM_LIST,'S02'),0,'',',뷰티')||
           DECODE(INSTR(ITEM_LIST,'S03'),0,'',',레저자동차')||
           DECODE(INSTR(ITEM_LIST,'S04'),0,'',',식품')||
           DECODE(INSTR(ITEM_LIST,'S05'),0,'',',생활건강')||
           DECODE(INSTR(ITEM_LIST,'S06'),0,'',',가구인테리어')||
           DECODE(INSTR(ITEM_LIST,'S07'),0,'',',가전')||
           DECODE(INSTR(ITEM_LIST,'S08'),0,'',',도서취미')||
           DECODE(INSTR(ITEM_LIST,'S09'),0,'',',컴퓨터')||
           DECODE(INSTR(ITEM_LIST,'S010'),0,'',',브랜드'),2) AS "관심품목명"
FROM TB_ETC_INFO;
    
NVL()
SELECT * FROM TB_CUSTOMER;
SELECT CUSTOMER_NM,NVL(PHONE_NUMBER,'000-0000-0000')AS "PHONE_NUMBER" FROM TB_CUSTOMER;

LEAST() 최소값
SELECT LEAST(13,5,-3,0,7,-10,200) AS LEAST_NM FROM DUAL;

GREATEST() 최대값
SELECT GREATEST(13,5,-3,0,7,-10,200) AS LEAST_NM FROM DUAL;


